# Generated by Django 2.0.2 on 2018-03-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dolaposcrumy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrumyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WT', 'Weekly Task'), ('DT', 'Daily Task'), ('V', 'Verified'), ('D', 'Done')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='status_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dolaposcrumy.ScrumyStatus'),
            preserve_default=False,
        ),
    ]
