# Generated by Django 2.0.2 on 2018-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dolaposcrumy', '0002_auto_20180317_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='status_id',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='task_category',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='user_id',
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='firstName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scrumyuser',
            name='lastName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scrumyuser',
            name='userName',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
