# Generated by Django 2.0.2 on 2018-03-18 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dolaposcrumy', '0005_auto_20180317_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='task_category',
        ),
    ]
